### ISSUE TITLE
Sublime 3211 is reporting an error at startup

### ISSUE THREAD

**Issue by mghcool** [tanepiper/SublimeText-Nodejs#103]
windows10
node-v10.18.1-x64
sublime 3211

info：
Building ...
fs.js:128

  throw new ERR_INVALID_CALLBACK();

  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

    at maybeCallback (fs.js:128:9)

    at Object.writeFile (fs.js:1163:14)

    at saveCompletion (C:\Users\MGH\AppData\Roaming\Sublime Text 3\Packages\Nodejs\tools\doc_builder.js:22:6)

    at createCompletions (C:\Users\MGH\AppData\Roaming\Sublime Text 3\Packages\Nodejs\tools\doc_builder.js:381:3)

    at exports.doc_builder (C:\Users\MGH\AppData\Roaming\Sublime Text 3\Packages\Nodejs\tools\doc_builder.js:228:5)

    at Object.<anonymous> (C:\Users\MGH\AppData\Roaming\Sublime Text 3\Packages\Nodejs\tools\default_build.js:8:1)

    at Module._compile (internal/modules/cjs/loader.js:778:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

    at Module.load (internal/modules/cjs/loader.js:653:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by varp** [comment]
Hi @mghcool , I am preparing a new release. I hope it will happen on this weekend

**Comment by KrookedZBoy** [comment]
@mghcool Has that released yet? I have a fresh install of sublime build 3211 and sublimetext-nodejs and I'm getting this error every time I open sublime text.

**Comment by varp** [comment]
@KrookedZBoy I'm sorry, but I could not find a time to do a new release.

**Comment by varp** [comment]
OK. In the situation of lockdown i've requested 2 days of holidays. I'll do a new release today. Please wait the further comment.

**Comment by varp** [comment]
I've made a new release v2.0.4. Should fix this issue. Feel free to reopen if it is not!
