### ISSUE TITLE
Error with tooltip

### ISSUE THREAD

**Issue by A-312** [tanepiper/SublimeText-Nodejs#107]
On windows, when I click in the menu: 
![image](https://user-images.githubusercontent.com/18501150/80363121-0b9b2900-8884-11ea-95a1-495f2b57bdd1.png)

I got:

```js
Exception in thread Thread-453:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\A-312\AppData\Roaming\Sublime Text 3\Packages\Nodejs\lib\nodejs_command_thread.py", line 125, in run
    output = self.proc.communicate(timeout=5)[0].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 81: invalid start byte
```

settings:

```json
// Settings in here override those in "Nodejs/Nodejs.sublime-settings",
// and are overridden in turn by syntax-specific settings.
{
  "node_path": "C:\\Users\\A-312\\AppData\\Roaming\\Sublime Text 3\\nodejs_bin\\node-v12.16.2-win-x64",
  "encoding": "utf8"
}
```

**Comment by varp** [comment]
That's very weird because all tests have been passed with success. Anyway, I'll try to reproduce your case and let you to know

**Comment by varp** [comment]
Please, post the version of ST you are using with build number.

**Comment by A-312** [comment]
3211 and I installed your package with package control
