### ISSUE TITLE
new error message from Nodejs

### ISSUE THREAD

**Issue by LandisTwo** [tanepiper/SublimeText-Nodejs#79]
I don't remember adding or changing anything, but I'm now getting the following error when I open any document/file and Nodejs is enabled.

`[Errno 2] No such file or directory: 'npm' `
`[cmd: ['npm', 'install', '-s']] `
`[dir: /home/landis/.config/sublime-text-3/Packages/Nodejs] `
`[path: /home/landis/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib64:/home/landis/.local:/home/landis/.local/share/icons:/usr/lib64:/home/landis/.local:/home/landis/.local/share/icons]`

I want to, don't know how to 'Force' re-install it through package-control.
I don't want to 'remove' and re-install it with package-control, because I don't know how packages are 'hooked' to other packages that depend on it in Sublime-Text3.
eg, HTML/CSS/jscript-prettify among others.
If Nodejs is called by other packages, it should be ok, like packages calling clib in Linux, but if they have hooks re-written the first time they were installed with versioning details, they will fail.

Landis.

p.s - Nodejs package.json

> {
>   "name": "sublime-nodejs",
>   "version": "1.5.6",
>   "description": "NPM Support file for the Sublime Text 3 Nodejs Plugin",
>   "dependencies": {
>     "commander": "^2.9.0",
>     "uglify-js": "^2.6.4",
>     "tern": "^0.21.0"
>   }
> }
**EDIT**
Just remembered. A week ago, when I started Sublime Text, a message said a 'Dependency was installed, restart ST3'. I wasted an hour trying to figure out What was installed and then gave up, assuming all was ok.. Not so, because I started getting the Nodejs NPM directory/file errors. I disabled Nodejs and now I want it back.

**Comment by varp** [comment]
Hello, I’ll a feedback later today

**Comment by varp** [comment]
Which version of ST3 are you using? 

>I want to, don't know how to 'Force' re-install it through package-control.

Could you reinstall the package? Also, I've released a new version 2.0.1 which possibly can solve your problem. 
```
ctrl+shift+p -> Remove package -> Type Nodejs -> Hit Enter
ctrl+shift+p -> Install Package -> Type Nodejs -> Hit Enter
```
After that can you select menu: 
- Perferences -> Browse Packages. The explorer window will be opened. 
- There locate `Nodejs` folder and create file `.debug_plugin`. 
- Restart ST3
- Go to the ST3 console by `ctrl+~` 
- Copy the whole output and paste it here

**Comment by LandisTwo** [comment]
@varp 
I was going to go through the steps you've laid out, but...
I enabled Nodejs and opened several files and No Errors.
(2017.12.14)
Just this morning, I did an up on my opensuse linux and one of the patches was Nodejs.
I installed the opensuse patch/update for nodejs-common.

Again, I get No errors opening files in ST3 build 3143.
(i prefer to use this build. I DON'T like the 'new', flat, 'smartphone' look All apps; incl'd kde5, firefox 50+, opensuse 'leap off', etc are moving towards.)

Thank You for responding.
Landis.

ps, something new: each time I open ST3, the command panel, at the bottom of window, that the nodejs error was displayed in, opens, but is empty. Why?

pps, so, unless the error starts again, I'm going to assume this issue is done and am not going to unistall nodejs. 

ppps, the output for Nodejs (not having unistalled, reinstalled):
```
DPI scale: 1.002
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/landis/.config/sublime-text-3/Packages
state path: /home/landis/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/landis/.config/sublime-text-3/Installed Packages
ignored_packages: ["CodeWrapper", "CSScomb", "CSSOrder", "LiveStyle", "SublimeText", "SyntaxFold", "Vintage"]
pre session restore time: 0.334013
startup time: 0.643657
first paint time: 0.66504
first paint time: 0.692671
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
reloading plugin 0_package_control_loader.10-shellenv
reloading plugin 0_package_control_loader.20-newterm
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin CMakeEditor.CMakeEditor
reloading plugin CSS Format.css_format
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin Character Table.Character Table
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Dictionaries.Dictionaries
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin Javascript Beautify.jsbeautify
reloading plugin Nodejs.Nodejs
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397494 => PLUGIN_PATH - /home/landis/.config/sublime-text-3/Packages/Nodejs
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397622 => PLUGIN_LIB_DIR - /home/landis/.config/sublime-text-3/Packages/Nodejs/lib
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397694 => PLUGIN_DEBUG_FILE - /home/landis/.config/sublime-text-3/Packages/Nodejs/.debug_plugin
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397762 => UGLIFY_PATH - /home/landis/.config/sublime-text-3/Packages/Nodejs/tools/uglify_js.js
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397821 => BUILDER_PATH - /home/landis/.config/sublime-text-3/Packages/Nodejs/tools/default_build.js
Nodejs Plugin - DEBUG - 2017-12-14T20:46:03.397925 => SHELLENV - ('/bin/bash', {'_': '/usr/bin/env\n\x1b[38;5;243mlandis\x1b(B\x1b[m\x1b[38;5;250m@\x1b(B\x1b[m\x1b[38;5;243mlinux-e6510\x1b(B\x1b[m\x1b[38;5;251m:\x1b(B\x1b[m\x1b[38;5;242m/opt/sublime_text>\x1b(B\x1b[mlogout', 'PWD': '/opt/sublime_text', 'LESSOPEN': 'lessopen.sh %s', 'XCURSOR_SIZE': '0', 'DM_CONTROL': '/var/run/xdmctl', 'MINICOM': '-c on', 'LESS_ADVANCED_PREPROCESSOR': 'no', 'OSTYPE': 'linux', 'HISTSIZE': '1000', 'XDM_MANAGED': 'method=classic', 'JAVA_ROOT': '/usr/lib64/jvm/jre', 'WINDOWPATH': '7', 'GTK2_RC_FILES': '/etc/gtk-2.0/gtkrc:/home/landis/.gtkrc-2.0:/home/landis/.kde4/share/config/gtkrc-2.0', 'SHLVL': '2', 'CVS_RSH': 'ssh', 'KDEDIRS': '/home/landis/.local/share/icons/:/home/landis/.local/share/icons/:', 'DISPLAY': ':0', 'SSH_AUTH_SOCK': '/tmp/ssh-Z0pgwcRzZzkc/agent.1329', 'LS_OPTIONS': '-N --color=tty -T 0', 'MAIL': '/var/spool/mail/landis', 'JRE_HOME': '/usr/lib64/jvm/jre', 'ALSA_CONFIG_PATH': '/etc/alsa-pulse.conf', 'GPG_TTY': 'not a tty', 'XDG_VTNR': '7', 'GPG_AGENT_INFO': '/tmp/gpg-VGZJg5/S.gpg-agent:1431:1', 'XCURSOR_THEME': 'Adwaita', 'CONFIG_SITE': '/usr/share/site/x86_64-unknown-linux-gnu', 'QT_SYSTEM_DIR': '/usr/share/desktop-data', 'KDE_FULL_SESSION': 'true', 'QT_PLUGIN_PATH': '/home/landis/.kde4/lib64/kde4/plugins/:/usr/lib64/kde4/plugins/', 'JAVA_HOME': '/usr/lib64/jvm/jre', 'XSESSION_IS_UP': 'yes', 'XDG_SEAT': 'seat0', 'MORE': '-sl', 'PS1': '\\[\\033[38;5;243m\\]\\u\\[\x1b(B\x1b[m\\]\\[\\033[38;5;250m\\]@\\[\x1b(B\x1b[m\\]\\[\\033[38;5;243m\\]\\h\\[\x1b(B\x1b[m\\]\\[\\033[38;5;251m\\]:\\[\x1b(B\x1b[m\\]\\[\\033[38;5;242m\\]\\w>\\[\x1b(B\x1b[m\\]', 'XDG_SESSION_ID': '1', 'AUDIODRIVER': 'pulseaudio', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-roeF9R9W6M,guid=dfd31d933b559615c42965b75a32f407', 'INPUTRC': '/home/landis/.inputrc', 'TERM': 'xterm', 'USE_FAM': '', 'XDG_DATA_DIRS': '/usr/share:/usr/share:/opt/kf5/share', 'GS_LIB': '/home/landis/.fonts', 'LESS': '-M -I -R', 'QT_IM_SWITCHER': 'imsw-multi', 'XDG_RUNTIME_DIR': '/run/user/1000', 'MACHTYPE': 'x86_64-suse-linux', 'HOSTNAME': 'linux-e6510.wild', 'LS_COLORS': 'no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.xz=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:', 'QEMU_AUDIO_DRV': 'pa', 'GTK_IM_MODULE': 'cedilla', 'PATH': '/home/landis/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib64:/home/landis/.local:/home/landis/.local/share/icons:/usr/lib64:/home/landis/.local:/home/landis/.local/share/icons', 'XMODIFIERS': '@im=local', 'CSHEDIT': 'emacs', 'PAGER': 'less', 'SHELL': '/bin/bash', 'COLORTERM': '1', 'NNTPSERVER': 'news', 'PYTHONSTARTUP': '/etc/pythonstart', 'TMPDIR': '/tmp', 'SESSION_MANAGER': 'local/linux-e6510.wild:@/tmp/.ICE-unix/1530,unix/linux-e6510.wild:/tmp/.ICE-unix/1530', 'WINDOWMANAGER': '/usr/bin/startkde', 'HOME': '/home/landis', 'G_FILENAME_ENCODING': '@locale,UTF-8,ISO-8859-15,CP1252', 'GTK_MODULES': 'canberra-gtk-module', 'KDE_MULTIHEAD': 'false', 'XAUTHLOCALHOSTNAME': 'linux-e6510.wild', 'XDG_CONFIG_DIRS': '/etc/xdg', 'USER': 'landis', 'DESKTOP_SESSION': 'kde-plasma-safe', 'XKEYSYMDB': '/usr/X11R6/lib/X11/XKeysymDB', 'G_BROKEN_FILENAMES': '1', 'HOSTTYPE': 'x86_64', 'QT_IM_MODULE': 'xim', 'LANG': 'en_US.UTF-8', 'SDL_AUDIODRIVER': 'pulse', 'LESSCLOSE': 'lessclose.sh %s %s', 'FROM_HEADER': '', 'KDE_SESSION_VERSION': '4', 'LESSKEY': '/etc/lesskey.bin', 'GTK_RC_FILES': '/etc/gtk/gtkrc:/home/landis/.gtkrc:/home/landis/.kde4/share/config/gtkrc', 'SSH_AGENT_PID': '1430', 'XNLSPATH': '/usr/share/X11/nls', 'LOGNAME': 'landis', 'XDG_CURRENT_DESKTOP': 'KDE', 'SSH_ASKPASS': '/usr/lib/ssh/ksshaskpass', 'CPU': 'x86_64', 'JAVA_BINDIR': '/usr/lib64/jvm/jre/bin', 'HOST': 'linux-e6510.wild', 'KDE_SESSION_UID': '1000', 'MANPATH': '/usr/local/man:/usr/share/man', 'PROFILEREAD': 'true'})
reloading plugin Nodejs.__init__
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarFolders.OpenFilesInFolderWindow
reloading plugin SideBarFolders.SideBarFolders
reloading plugin WordHighlight.word_highlight
reloading plugin CodeFormatter.CodeFormatter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/landis/.config/sublime-text-3/Packages/CodeFormatter/CodeFormatter.py", line 26, in <module>
    from .codeformatter.formatter import Formatter
  File "/home/landis/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/formatter.py", line 23, in <module>
    from .scssformatter import ScssFormatter
  File "/home/landis/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/scssformatter.py", line 6, in <module>
    import scssbeautifier
  File "/home/landis/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/scssbeautifier/__init__.py", line 31, in <module>
    from cssbeautifier.css.options import BeautifierOptions
ImportError: No module named 'cssbeautifier.css'
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SFTP.SFTP
plugins loaded
Nodejs Plugin - INFO - 2017-12-14T20:46:03.953799 => Running `npm install` to install plugin dependencies
Nodejs Plugin - INFO - 2017-12-14T20:46:03.964660 => Running `node_builddocs` to generate Node.js completions
Package Control: Skipping automatic upgrade, last run at 2017-12-14 20:25:17, next run at 2017-12-14 21:25:17 or after
```
Thanks Again.

**Comment by varp** [comment]
Ok. According to the output you send me. There is no errors related to the plugin.  But looking at the error message in the first comment I can do assumption. in version 2 I’ve added ability to auto-install the plugin dependencies. I think in moment of installing you was not have any version of /node/ or /npm/
