### ISSUE TITLE
Sublime 3180 is reporting an error at startup

### ISSUE THREAD

**Issue by macrohard** [tanepiper/SublimeText-Nodejs#96]
Building ...
fs.js:136
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:136:9)
    at Object.writeFile (fs.js:1182:14)
    at saveCompletion (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:22:6)
    at createCompletions (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:381:3)
    at /Users/admin/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:228:5
    at Object.<anonymous> (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/default_build.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

**Comment by macrohard** [comment]
This bug has been fixed, but a warning will still pop up when Sublime starts:
```
Building ...
(node:12047) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
Done!
```
My Node.js version is 11.3.0

**Comment by varp** [comment]
@macrohard I'm planning to work on this project on New Year's Holidays

**Comment by uran1980** [comment]
Has may be the same error

```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at saveCompletion (/home/uran1980/.config/sublime-text-3/Packages/Nodejs/tools/doc_builder.js:22:6)
    at createCompletions (/home/uran1980/.config/sublime-text-3/Packages/Nodejs/tools/doc_builder.js:381:3)
    at exports.doc_builder (/home/uran1980/.config/sublime-text-3/Packages/Nodejs/tools/doc_builder.js:228:5)
    at Object.<anonymous> (/home/uran1980/.config/sublime-text-3/Packages/Nodejs/tools/default_build.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```
my node version is v10.15.0

**Comment by tgentet-obrien** [comment]
Is there an update on this? I am getting an error on startup also:

> Building ...
fs.js:159
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:159:9)
    at Object.fs.writeFile (fs.js:1278:14)
    at saveCompletion (/Users/timothygentet-obrien/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:22:6)
    at createCompletions (/Users/timothygentet-obrien/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:381:3)
    at exports.doc_builder (/Users/timothygentet-obrien/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/doc_builder.js:228:5)
    at Object.<anonymous> (/Users/timothygentet-obrien/Library/Application Support/Sublime Text 3/Packages/Nodejs/tools/default_build.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
