### ISSUE TITLE
No module name AIX

### ISSUE THREAD

**Issue by jingyuexing** [tanepiper/SublimeText-Nodejs#98]
reloading plugin Nodejs.Nodejs
Traceback (most recent call last):
  File "F:\IDEA\Sublime Text Build 3180 x64\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "F:\IDEA\Sublime Text Build 3180 x64\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\IDEA\Sublime Text Build 3180 x64\Data\Installed Packages\Nodejs.sublime-package\Nodejs.py", line 14, in <module>
  File "F:\IDEA\Sublime Text Build 3180 x64\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\IDEA\Sublime Text Build 3180 x64\Data\Installed Packages\Nodejs.sublime-package\lib/nodejs_commands.py", line 3, in <module>
  File "F:\IDEA\Sublime Text Build 3180 x64\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\IDEA\Sublime Text Build 3180 x64\Data\Installed Packages\Nodejs.sublime-package\lib/nodejs_base.py", line 7, in <module>
  File "F:\IDEA\Sublime Text Build 3180 x64\Data\Packages\psutil\st3_windows_x64\psutil\__init__.py", line 77, in <module>
    from ._common import AIX
ImportError: cannot import name AIX

**Comment by varp** [comment]
Hi, could you attach info about target platform ?

**Comment by varp** [comment]
Also info about ST version

**Comment by vaanwd** [comment]
I have the same error:
```
reloading plugin Nodejs.__init__
reloading plugin Nodejs.Nodejs
Traceback (most recent call last):
  File "D:\Share2\Programare\Editoare\Sublime Text\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Share2\Programare\Editoare\Sublime Text\Sublime Text 3\Data\Packages\Nodejs\Nodejs.py", line 14, in <module>
    from .lib.nodejs_commands import *
  File "D:\Share2\Programare\Editoare\Sublime Text\Sublime Text 3\Data\Packages\Nodejs\lib\nodejs_commands.py", line 3, in <module>
    from .nodejs_base import *
  File "D:\Share2\Programare\Editoare\Sublime Text\Sublime Text 3\Data\Packages\Nodejs\lib\nodejs_base.py", line 7, in <module>
    import psutil
  File "D:\Share2\PROGRA~1\Editoare\SUBLIM~1\SUBLIM~2\Data\Packages\psutil\ST3_WI~1\psutil\__init__.py", line 77, in <module>
    from ._common import AIX
ImportError: cannot import name AIX
```
---

Windows 7 x64, ST 3 Build 3207

**Comment by jingyuexing** [comment]
> Also info about ST version

Sublime Text Build 3180 x64 
Windows 10,
nodejs version 11.3

**Comment by vaanwd** [comment]
You need to add:
`AIX = sys.platform.startswith("aix")`
in `psutil\st3_windows_x32\psutil\_common.py` and `psutil\st3_windows_x64\psutil\_common.py`
after:
`SUNOS = sys.platform.startswith("sunos") or sys.platform.startswith("solaris")`

**Comment by varp** [comment]
> You need to add:
> `AIX = sys.platform.startswith("aix")`
> in `psutil\st3_windows_x32\psutil\_common.py` and `psutil\st3_windows_x64\psutil\_common.py`
> after:
> `SUNOS = sys.platform.startswith("sunos") or sys.platform.startswith("solaris")`

There is the original code from `psutil` authors. I've not modified the code at all. I've only modified the code in `setup.py` for compiling static versions of dynamic libraries.
